import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const getRoboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BerrySoft",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${getRoboto.variable} antialiased`}>{children}</body>
    </html>
  );
}
